package com.template.cxf.client.simple;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-13T09:43:47.852+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "MpUvrWebSvrSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MpUvrWebSvrSoap {

    /**
     * 发送模板消息
     */
    @WebMethod(operationName = "SendClassAlertTemplateMsgFor4", action = "http://tempuri.org/SendClassAlertTemplateMsgFor4")
    @RequestWrapper(localName = "SendClassAlertTemplateMsgFor4", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendClassAlertTemplateMsgFor4")
    @ResponseWrapper(localName = "SendClassAlertTemplateMsgFor4Response", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendClassAlertTemplateMsgFor4Response")
    @WebResult(name = "SendClassAlertTemplateMsgFor4Result", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity sendClassAlertTemplateMsgFor4(
            @WebParam(name = "openId", targetNamespace = "http://tempuri.org/")
                    String openId,
            @WebParam(name = "templateId", targetNamespace = "http://tempuri.org/")
                    String templateId,
            @WebParam(name = "url", targetNamespace = "http://tempuri.org/")
                    String url,
            @WebParam(name = "firstData", targetNamespace = "http://tempuri.org/")
                    String firstData,
            @WebParam(name = "remark", targetNamespace = "http://tempuri.org/")
                    String remark,
            @WebParam(name = "keyWords1", targetNamespace = "http://tempuri.org/")
                    String keyWords1,
            @WebParam(name = "keyWords2", targetNamespace = "http://tempuri.org/")
                    String keyWords2,
            @WebParam(name = "keyWords3", targetNamespace = "http://tempuri.org/")
                    String keyWords3,
            @WebParam(name = "keyWords4", targetNamespace = "http://tempuri.org/")
                    String keyWords4
    );

    /**
     * 根据AppId获取Token
     */
    @WebMethod(operationName = "GetAccessTokenByAppId", action = "http://tempuri.org/GetAccessTokenByAppId")
    @RequestWrapper(localName = "GetAccessTokenByAppId", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetAccessTokenByAppId")
    @ResponseWrapper(localName = "GetAccessTokenByAppIdResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetAccessTokenByAppIdResponse")
    @WebResult(name = "GetAccessTokenByAppIdResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity getAccessTokenByAppId(
            @WebParam(name = "appId", targetNamespace = "http://tempuri.org/")
                    String appId
    );

    /**
     * 获取微信MP的AccessToken
     */
    @WebMethod(operationName = "GetMpAccessToken", action = "http://tempuri.org/GetMpAccessToken")
    @RequestWrapper(localName = "GetMpAccessToken", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetMpAccessToken")
    @ResponseWrapper(localName = "GetMpAccessTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetMpAccessTokenResponse")
    @WebResult(name = "GetMpAccessTokenResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity getMpAccessToken();

    /**
     * 发送客服文本消息
     */
    @WebMethod(operationName = "SendKFTextMsgByAppId", action = "http://tempuri.org/SendKFTextMsgByAppId")
    @RequestWrapper(localName = "SendKFTextMsgByAppId", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendKFTextMsgByAppId")
    @ResponseWrapper(localName = "SendKFTextMsgByAppIdResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendKFTextMsgByAppIdResponse")
    @WebResult(name = "SendKFTextMsgByAppIdResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity sendKFTextMsgByAppId(
            @WebParam(name = "appId", targetNamespace = "http://tempuri.org/")
                    String appId,
            @WebParam(name = "openId", targetNamespace = "http://tempuri.org/")
                    String openId,
            @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
                    String content
    );

    /**
     * 获取活动二维码
     */
    @WebMethod(operationName = "GetCampaignQRCode", action = "http://tempuri.org/GetCampaignQRCode")
    @RequestWrapper(localName = "GetCampaignQRCode", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetCampaignQRCode")
    @ResponseWrapper(localName = "GetCampaignQRCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetCampaignQRCodeResponse")
    @WebResult(name = "GetCampaignQRCodeResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity getCampaignQRCode(
            @WebParam(name = "qrcodeInfo", targetNamespace = "http://tempuri.org/")
                    QrcodeInfo qrcodeInfo
    );

    /**
     * 更新兑换记录
     */
    @WebMethod(operationName = "Update_Prestige400gCampaignConfirmData", action = "http://tempuri.org/Update_Prestige400gCampaignConfirmData")
    @RequestWrapper(localName = "Update_Prestige400gCampaignConfirmData", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.UpdatePrestige400GCampaignConfirmData")
    @ResponseWrapper(localName = "Update_Prestige400gCampaignConfirmDataResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.UpdatePrestige400GCampaignConfirmDataResponse")
    @WebResult(name = "Update_Prestige400gCampaignConfirmDataResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity updatePrestige400GCampaignConfirmData(
            @WebParam(name = "openId", targetNamespace = "http://tempuri.org/")
                    String openId
    );

    /**
     * KA机制二获取活动编码
     */
    @WebMethod(operationName = "CheckAndGetKA2Code", action = "http://tempuri.org/CheckAndGetKA2Code")
    @RequestWrapper(localName = "CheckAndGetKA2Code", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.CheckAndGetKA2Code")
    @ResponseWrapper(localName = "CheckAndGetKA2CodeResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.CheckAndGetKA2CodeResponse")
    @WebResult(name = "CheckAndGetKA2CodeResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity checkAndGetKA2Code(
            @WebParam(name = "fanscampaignId", targetNamespace = "http://tempuri.org/")
                    String fanscampaignId,
            @WebParam(name = "openid", targetNamespace = "http://tempuri.org/")
                    String openid
    );

    /**
     * 检测或同步企业微信HIH暗码
     */
    @WebMethod(operationName = "CheckHihBindedCode", action = "http://tempuri.org/CheckHihBindedCode")
    @RequestWrapper(localName = "CheckHihBindedCode", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.CheckHihBindedCode")
    @ResponseWrapper(localName = "CheckHihBindedCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.CheckHihBindedCodeResponse")
    @WebResult(name = "CheckHihBindedCodeResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity checkHihBindedCode(
            @WebParam(name = "json", targetNamespace = "http://tempuri.org/")
                    String json
    );

    /**
     * 生成永久二维码
     */
    @WebMethod(operationName = "GetPermanentQRCodeWithPara", action = "http://tempuri.org/GetPermanentQRCodeWithPara")
    @RequestWrapper(localName = "GetPermanentQRCodeWithPara", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetPermanentQRCodeWithPara")
    @ResponseWrapper(localName = "GetPermanentQRCodeWithParaResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetPermanentQRCodeWithParaResponse")
    @WebResult(name = "GetPermanentQRCodeWithParaResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity getPermanentQRCodeWithPara(
            @WebParam(name = "scene_id_str", targetNamespace = "http://tempuri.org/")
                    String sceneIdStr
    );

    /**
     * 获取微信MP的jsapi_ticket(带有效期信息)
     */
    @WebMethod(operationName = "Getjsapi_ticket2", action = "http://tempuri.org/Getjsapi_ticket2")
    @RequestWrapper(localName = "Getjsapi_ticket2", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetjsapiTicket2")
    @ResponseWrapper(localName = "Getjsapi_ticket2Response", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetjsapiTicket2Response")
    @WebResult(name = "Getjsapi_ticket2Result", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiJsTicketResult getjsapiTicket2();

    /**
     * 生成品牌带参数的临时二维码
     */
    @WebMethod(operationName = "GetTempQrCodeWithPara", action = "http://tempuri.org/GetTempQrCodeWithPara")
    @RequestWrapper(localName = "GetTempQrCodeWithPara", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetTempQrCodeWithPara")
    @ResponseWrapper(localName = "GetTempQrCodeWithParaResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetTempQrCodeWithParaResponse")
    @WebResult(name = "GetTempQrCodeWithParaResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity getTempQrCodeWithPara(
            @WebParam(name = "scene_id", targetNamespace = "http://tempuri.org/")
                    int sceneId,
            @WebParam(name = "expire_seconds", targetNamespace = "http://tempuri.org/")
                    int expireSeconds
    );

    /**
     * 根据AppId获取微信MP的jsapi_ticket(带有效期信息)
     */
    @WebMethod(operationName = "GetJsApiTicket", action = "http://tempuri.org/GetJsApiTicket")
    @RequestWrapper(localName = "GetJsApiTicket", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetJsApiTicket3")
    @ResponseWrapper(localName = "GetJsApiTicketResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetJsApiTicketResponse2")
    @WebResult(name = "GetJsApiTicketResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiJsTicketResult getJsApiTicket(
            @WebParam(name = "appId", targetNamespace = "http://tempuri.org/")
                    String appId
    );

    /**
     * 发送客服文本消息
     */
    @WebMethod(operationName = "SendKFTextMsg", action = "http://tempuri.org/SendKFTextMsg")
    @RequestWrapper(localName = "SendKFTextMsg", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendKFTextMsg")
    @ResponseWrapper(localName = "SendKFTextMsgResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendKFTextMsgResponse")
    @WebResult(name = "SendKFTextMsgResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity sendKFTextMsg(
            @WebParam(name = "openId", targetNamespace = "http://tempuri.org/")
                    String openId,
            @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
                    String content
    );

    /**
     * 生成品牌带参数的临时二维码
     */
    @WebMethod(operationName = "GetTempQrCodeByAppId", action = "http://tempuri.org/GetTempQrCodeByAppId")
    @RequestWrapper(localName = "GetTempQrCodeByAppId", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetTempQrCodeByAppId")
    @ResponseWrapper(localName = "GetTempQrCodeByAppIdResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetTempQrCodeByAppIdResponse")
    @WebResult(name = "GetTempQrCodeByAppIdResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity getTempQrCodeByAppId(
            @WebParam(name = "scene_id", targetNamespace = "http://tempuri.org/")
                    int sceneId,
            @WebParam(name = "appId", targetNamespace = "http://tempuri.org/")
                    String appId,
            @WebParam(name = "expire_seconds", targetNamespace = "http://tempuri.org/")
                    int expireSeconds
    );

    /**
     * 同步皇家卡券Code
     */
    @WebMethod(operationName = "SendCrmCardTemplate", action = "http://tempuri.org/SendCrmCardTemplate")
    @RequestWrapper(localName = "SendCrmCardTemplate", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendCrmCardTemplate")
    @ResponseWrapper(localName = "SendCrmCardTemplateResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendCrmCardTemplateResponse")
    @WebResult(name = "SendCrmCardTemplateResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity sendCrmCardTemplate(
            @WebParam(name = "campaignCode", targetNamespace = "http://tempuri.org/")
                    String campaignCode,
            @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
                    String cardId,
            @WebParam(name = "cardCode", targetNamespace = "http://tempuri.org/")
                    String cardCode,
            @WebParam(name = "openId", targetNamespace = "http://tempuri.org/")
                    String openId
    );

    /**
     * 获取微信MP的卡券Ticket
     */
    @WebMethod(operationName = "Getjscard_api_ticket", action = "http://tempuri.org/Getjscard_api_ticket")
    @RequestWrapper(localName = "Getjscard_api_ticket", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetjscardApiTicket")
    @ResponseWrapper(localName = "Getjscard_api_ticketResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetjscardApiTicketResponse")
    @WebResult(name = "Getjscard_api_ticketResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity getjscardApiTicket(
            @WebParam(name = "accesstoken", targetNamespace = "http://tempuri.org/")
                    String accesstoken
    );

    /**
     * 根据用户Id查询用户是否关注
     */
    @WebMethod(operationName = "GetSubStatusByBBTUID", action = "http://tempuri.org/GetSubStatusByBBTUID")
    @RequestWrapper(localName = "GetSubStatusByBBTUID", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetSubStatusByBBTUID")
    @ResponseWrapper(localName = "GetSubStatusByBBTUIDResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetSubStatusByBBTUIDResponse")
    @WebResult(name = "GetSubStatusByBBTUIDResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity getSubStatusByBBTUID(
            @WebParam(name = "uid", targetNamespace = "http://tempuri.org/")
                    String uid
    );

    /**
     * 注册有礼二维码 发送模板消息
     */
    @WebMethod(operationName = "SendTemplateMsgForGiftSucc", action = "http://tempuri.org/SendTemplateMsgForGiftSucc")
    @RequestWrapper(localName = "SendTemplateMsgForGiftSucc", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendTemplateMsgForGiftSucc")
    @ResponseWrapper(localName = "SendTemplateMsgForGiftSuccResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendTemplateMsgForGiftSuccResponse")
    @WebResult(name = "SendTemplateMsgForGiftSuccResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity sendTemplateMsgForGiftSucc(
            @WebParam(name = "openId", targetNamespace = "http://tempuri.org/")
                    String openId,
            @WebParam(name = "url", targetNamespace = "http://tempuri.org/")
                    String url,
            @WebParam(name = "firstData", targetNamespace = "http://tempuri.org/")
                    String firstData,
            @WebParam(name = "keyWords1", targetNamespace = "http://tempuri.org/")
                    String keyWords1,
            @WebParam(name = "keyWords2", targetNamespace = "http://tempuri.org/")
                    String keyWords2,
            @WebParam(name = "remark", targetNamespace = "http://tempuri.org/")
                    String remark
    );

    /**
     * 同步卡券Code
     */
    @WebMethod(operationName = "SynchCardCode", action = "http://tempuri.org/SynchCardCode")
    @RequestWrapper(localName = "SynchCardCode", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SynchCardCode")
    @ResponseWrapper(localName = "SynchCardCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SynchCardCodeResponse")
    @WebResult(name = "SynchCardCodeResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity synchCardCode(
            @WebParam(name = "campaignCode", targetNamespace = "http://tempuri.org/")
                    String campaignCode,
            @WebParam(name = "openId", targetNamespace = "http://tempuri.org/")
                    String openId,
            @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
                    String cardId,
            @WebParam(name = "cardCode", targetNamespace = "http://tempuri.org/")
                    String cardCode,
            @WebParam(name = "startTime", targetNamespace = "http://tempuri.org/")
                    String startTime,
            @WebParam(name = "endTime", targetNamespace = "http://tempuri.org/")
                    String endTime
    );

    /**
     * 发送模板消息
     */
    @WebMethod(operationName = "SendTemplateMsgCommon", action = "http://tempuri.org/SendTemplateMsgCommon")
    @RequestWrapper(localName = "SendTemplateMsgCommon", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendTemplateMsgCommon")
    @ResponseWrapper(localName = "SendTemplateMsgCommonResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendTemplateMsgCommonResponse")
    @WebResult(name = "SendTemplateMsgCommonResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity sendTemplateMsgCommon(
            @WebParam(name = "openId", targetNamespace = "http://tempuri.org/")
                    String openId,
            @WebParam(name = "templateId", targetNamespace = "http://tempuri.org/")
                    String templateId,
            @WebParam(name = "firstData", targetNamespace = "http://tempuri.org/")
                    String firstData,
            @WebParam(name = "remark", targetNamespace = "http://tempuri.org/")
                    String remark,
            @WebParam(name = "keywords", targetNamespace = "http://tempuri.org/")
                    ArrayOfString keywords,
            @WebParam(name = "url", targetNamespace = "http://tempuri.org/")
                    String url
    );

    /**
     * 根据OpenId绑定手机号
     */
    @WebMethod(operationName = "BindFansMobileByOpenId", action = "http://tempuri.org/BindFansMobileByOpenId")
    @RequestWrapper(localName = "BindFansMobileByOpenId", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.BindFansMobileByOpenId")
    @ResponseWrapper(localName = "BindFansMobileByOpenIdResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.BindFansMobileByOpenIdResponse")
    @WebResult(name = "BindFansMobileByOpenIdResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity bindFansMobileByOpenId(
            @WebParam(name = "openId", targetNamespace = "http://tempuri.org/")
                    String openId,
            @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
                    String mobile
    );

    /**
     * 查询品牌微信粉丝OpenId
     */
    @WebMethod(operationName = "GetFrisoMasterOpenId", action = "http://tempuri.org/GetFrisoMasterOpenId")
    @RequestWrapper(localName = "GetFrisoMasterOpenId", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetFrisoMasterOpenId")
    @ResponseWrapper(localName = "GetFrisoMasterOpenIdResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetFrisoMasterOpenIdResponse")
    @WebResult(name = "GetFrisoMasterOpenIdResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity getFrisoMasterOpenId(
            @WebParam(name = "openId", targetNamespace = "http://tempuri.org/")
                    String openId
    );

    /**
     * 核销卡券自定义
     */
    @WebMethod(operationName = "CardConsume", action = "http://tempuri.org/CardConsume")
    @RequestWrapper(localName = "CardConsume", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.CardConsume")
    @ResponseWrapper(localName = "CardConsumeResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.CardConsumeResponse")
    @WebResult(name = "CardConsumeResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity cardConsume(
            @WebParam(name = "appId", targetNamespace = "http://tempuri.org/")
                    String appId,
            @WebParam(name = "camcode", targetNamespace = "http://tempuri.org/")
                    String camcode,
            @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
                    String code,
            @WebParam(name = "cardId", targetNamespace = "http://tempuri.org/")
                    String cardId
    );

    /**
     * 发送模板消息
     */
    @WebMethod(operationName = "SendTemplateMsg", action = "http://tempuri.org/SendTemplateMsg")
    @RequestWrapper(localName = "SendTemplateMsg", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendTemplateMsg")
    @ResponseWrapper(localName = "SendTemplateMsgResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendTemplateMsgResponse")
    @WebResult(name = "SendTemplateMsgResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity sendTemplateMsg(
            @WebParam(name = "openId", targetNamespace = "http://tempuri.org/")
                    String openId,
            @WebParam(name = "obj", targetNamespace = "http://tempuri.org/")
                    TemplateNews obj
    );

    /**
     * 发送开课提醒模板消息
     */
    @WebMethod(operationName = "SendClassAlertTemplateMsg", action = "http://tempuri.org/SendClassAlertTemplateMsg")
    @RequestWrapper(localName = "SendClassAlertTemplateMsg", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendClassAlertTemplateMsg")
    @ResponseWrapper(localName = "SendClassAlertTemplateMsgResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendClassAlertTemplateMsgResponse")
    @WebResult(name = "SendClassAlertTemplateMsgResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity sendClassAlertTemplateMsg(
            @WebParam(name = "openId", targetNamespace = "http://tempuri.org/")
                    String openId,
            @WebParam(name = "templateId", targetNamespace = "http://tempuri.org/")
                    String templateId,
            @WebParam(name = "url", targetNamespace = "http://tempuri.org/")
                    String url,
            @WebParam(name = "firstData", targetNamespace = "http://tempuri.org/")
                    String firstData,
            @WebParam(name = "remark", targetNamespace = "http://tempuri.org/")
                    String remark,
            @WebParam(name = "keyWords1", targetNamespace = "http://tempuri.org/")
                    String keyWords1,
            @WebParam(name = "keyWords2", targetNamespace = "http://tempuri.org/")
                    String keyWords2,
            @WebParam(name = "keyWords3", targetNamespace = "http://tempuri.org/")
                    String keyWords3
    );

    /**
     * 获取粉丝绑定状态及手机号
     */
    @WebMethod(operationName = "GetFansBindMobile", action = "http://tempuri.org/GetFansBindMobile")
    @RequestWrapper(localName = "GetFansBindMobile", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetFansBindMobile")
    @ResponseWrapper(localName = "GetFansBindMobileResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetFansBindMobileResponse")
    @WebResult(name = "GetFansBindMobileResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity getFansBindMobile(
            @WebParam(name = "openId", targetNamespace = "http://tempuri.org/")
                    String openId
    );

    /**
     * 获取消费者皇家赠品信息
     */
    @WebMethod(operationName = "SendKingGift", action = "http://tempuri.org/SendKingGift")
    @RequestWrapper(localName = "SendKingGift", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendKingGift")
    @ResponseWrapper(localName = "SendKingGiftResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendKingGiftResponse")
    @WebResult(name = "SendKingGiftResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity sendKingGift(
            @WebParam(name = "vCusGiftInfo", targetNamespace = "http://tempuri.org/")
                    com.template.cxf.client.simple.VCustomerGiftInfo vCusGiftInfo
    );

    /**
     * 发送图文
     */
    @WebMethod(operationName = "SendNews", action = "http://tempuri.org/SendNews")
    @RequestWrapper(localName = "SendNews", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendNews")
    @ResponseWrapper(localName = "SendNewsResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.SendNewsResponse")
    @WebResult(name = "SendNewsResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity sendNews(
            @WebParam(name = "sendWechatNews", targetNamespace = "http://tempuri.org/")
                    SendWechatNews sendWechatNews
    );

    /**
     * 获取微信MP的jsapi_ticket
     */
    @WebMethod(operationName = "Getjsapi_ticket", action = "http://tempuri.org/Getjsapi_ticket")
    @RequestWrapper(localName = "Getjsapi_ticket", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetjsapiTicket")
    @ResponseWrapper(localName = "Getjsapi_ticketResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetjsapiTicketResponse")
    @WebResult(name = "Getjsapi_ticketResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity getjsapiTicket(
            @WebParam(name = "accesstoken", targetNamespace = "http://tempuri.org/")
                    String accesstoken
    );

    /**
     * 根据用户Id生成个性二维码
     */
    @WebMethod(operationName = "GetQrCodeByBBTUID", action = "http://tempuri.org/GetQrCodeByBBTUID")
    @RequestWrapper(localName = "GetQrCodeByBBTUID", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetQrCodeByBBTUID")
    @ResponseWrapper(localName = "GetQrCodeByBBTUIDResponse", targetNamespace = "http://tempuri.org/", className = "com.template.cxf.client.simple.GetQrCodeByBBTUIDResponse")
    @WebResult(name = "GetQrCodeByBBTUIDResult", targetNamespace = "http://tempuri.org/")
    public com.template.cxf.client.simple.WebApiResultEntity getQrCodeByBBTUID(
            @WebParam(name = "uid", targetNamespace = "http://tempuri.org/")
                    String uid
    );
}
