package com.template.cxf.client.simple;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-13T09:43:47.909+08:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "MpUvrWebSvr",
                  wsdlLocation = "http://cheil.wedochina.cn/webservice/MpUvrWebSvr.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class MpUvrWebSvr extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "MpUvrWebSvr");
    public final static QName MpUvrWebSvrSoap = new QName("http://tempuri.org/", "MpUvrWebSvrSoap");
    public final static QName MpUvrWebSvrSoap12 = new QName("http://tempuri.org/", "MpUvrWebSvrSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://cheil.wedochina.cn/webservice/MpUvrWebSvr.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MpUvrWebSvr.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://cheil.wedochina.cn/webservice/MpUvrWebSvr.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MpUvrWebSvr(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MpUvrWebSvr(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MpUvrWebSvr() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MpUvrWebSvr(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MpUvrWebSvr(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MpUvrWebSvr(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MpUvrWebSvrSoap
     */
    @WebEndpoint(name = "MpUvrWebSvrSoap")
    public MpUvrWebSvrSoap getMpUvrWebSvrSoap() {
        return super.getPort(MpUvrWebSvrSoap, MpUvrWebSvrSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MpUvrWebSvrSoap
     */
    @WebEndpoint(name = "MpUvrWebSvrSoap")
    public MpUvrWebSvrSoap getMpUvrWebSvrSoap(WebServiceFeature... features) {
        return super.getPort(MpUvrWebSvrSoap, MpUvrWebSvrSoap.class, features);
    }


    /**
     *
     * @return
     *     returns MpUvrWebSvrSoap
     */
    @WebEndpoint(name = "MpUvrWebSvrSoap12")
    public MpUvrWebSvrSoap getMpUvrWebSvrSoap12() {
        return super.getPort(MpUvrWebSvrSoap12, MpUvrWebSvrSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MpUvrWebSvrSoap
     */
    @WebEndpoint(name = "MpUvrWebSvrSoap12")
    public MpUvrWebSvrSoap getMpUvrWebSvrSoap12(WebServiceFeature... features) {
        return super.getPort(MpUvrWebSvrSoap12, MpUvrWebSvrSoap.class, features);
    }

}
